# SonarQube Cloud Configuration
# Project: alex_assignment
# Organization: phatla

sonar.projectKey=PhaTLa_alex_assignment
sonar.organization=phatla
sonar.sources=app/src
sonar.python.version=3.9
sonar.qualitygate.wait=true
