# SonarQube Cloud Configuration
# Project: elsa_assignment
# Organization: phatla

sonar.projectKey=PhaTLa_elsa_assignment
sonar.organization=phatla
sonar.sources=app/src
sonar.python.version=3.9
sonar.qualitygate.wait=true
