apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-additional
  namespace: monitoring
data:
  quote-api.yaml: |
    - job_name: quote-api
      kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - default
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          action: keep
          regex: quote-api
        - source_labels: [__meta_kubernetes_pod_port_name]
          action: keep
          regex: metrics
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
