{
 "title": "Quote API Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate (req/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(quote_api_requests_total[1m]))",
     "legendFormat": "Requests/sec"
    }
   ]
  },
  {
   "title": "Latency p95 (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(quote_api_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p95 Latency"
    }
   ]
  },
  {
   "title": "Replica Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment='quote-api'}",
     "legendFormat": "Replicas"
    }
   ]
  },
  {
   "title": "CPU Usage (Cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~'quote-api-.*'}[5m]))",
     "legendFormat": "CPU Usage"
    }
   ]
  }
 ]
}